import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>API LevelUp</h1>
        <h3>Para pegar todos os levels, utilize a rota /api/levels</h3>
        <h3>Para pegar um level especifico, utilize a rota /api/levels/(level)</h3>
      </main>
    </>
  );
}